# Generated by Django 5.1 on 2024-09-04 09:55

from django.db import migrations
 

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_promotion_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('colletion1')                  
        """, """
           DELETE FROM store_collection
           WHERE title='collection1' 
              
        """)
    ]
