# Generated by Django 5.1 on 2024-09-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240904_0955'),
    ]

    operations = [
    ]
