# Generated by Django 5.1 on 2024-09-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20240905_0901'),
    ]

    operations = [
    ]
