# Generated by Django 5.1 on 2024-09-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20240905_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_stats',
            new_name='payment_status',
        ),
    ]
