# Generated by Django 5.1 on 2024-08-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedItem',
        ),
    ]
