# Generated by Django 5.1.1 on 2024-10-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_delete_likeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='object_id',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
